### ISSUE TITLE
error in an-qrcode.module.d.ts:1:22 when add AnQrcodeModule  to my appModule

### ISSUE THREAD

**Issue by amirmostafa** [naimmalek/an-qrcode#2]
ERROR in node_modules/an-qrcode/lib/an-qrcode.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (an-qrcode) which declares AnQrcodeModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version
 of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by naimmalek** [comment]
@amirmostafa, which angular version are you using?

**Comment by naimmalek** [comment]
should be fixed in latest update
