### ISSUE TITLE
get data image

### ISSUE THREAD

**Issue by StebSan** [naimmalek/an-qrcode#3]
Thanks for proyect.

i would like know how get data base64 result of image

Thanks.

**Comment by naimmalek** [comment]
@StebSan ,

which data you want to get?

**Comment by StebSan** [comment]
Hi @naimmalek 

I would like work with the information in src

`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATs....." />`

is equal a the data in console

 "this.result **data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATs.....**"

thanks friend.
