### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by inexuscore** [naimmalek/an-qrcode#5]
Hello,
Is this repo actively maintained? I need to upgrade to Angular 11 and the only package in my dependencies that's blocking me is this one. Any plans to update soon?
Thanks a lot.

**Comment by naimmalek** [comment]
Hi @inexuscore, 
Yes work in progress. You will get upgraded version soon. 
Thanks

**Comment by inexuscore** [comment]
@naimmalek Fantastic! Looking forward to it, thank you very much.

**Comment by naimmalek** [comment]
Hi @inexuscore, 
Upgraded version are available now.
Thanks

**Comment by inexuscore** [comment]
@naimmalek Fabulous. Thank you very much for the quick update, cheers.
